/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorMascota;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import modelo.Mascota;

/**
 *
 * @author william
 */
public class MantenedorMascota extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public MantenedorMascota() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        lblEtiqueta.setText("NOMBRE: ");
        ckbBuscNombre.setSelected(true);
        txtNombreMascota.setVisible(true);
        DefaultTableModel dtm =  (DefaultTableModel) tblMascotas.getModel();
        dtm.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnAlmacenar = new javax.swing.JButton();
        btnMantenedor1 = new javax.swing.JButton();
        btnAbout1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblEtiqueta = new javax.swing.JLabel();
        txtNombreMascota = new javax.swing.JTextField();
        cbbTipoMascota = new javax.swing.JComboBox<>();
        ckbBuscNombre = new javax.swing.JCheckBox();
        ckbBuscTipo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMascotas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnInicio1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MEDIPET");
        setBounds(new java.awt.Rectangle(600, 250, 766, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(766, 500));

        jPanel1.setBackground(new java.awt.Color(160, 172, 72));

        btnAlmacenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAlmacenar.setText("ALMACENAR MASCOTA");
        btnAlmacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlmacenar);

        btnMantenedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MANTENEDOR.png"))); // NOI18N
        btnMantenedor1.setText("MANTENEDOR MASCOTAS");
        btnMantenedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenedor1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMantenedor1);

        btnAbout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/QUIENES SOMOS.png"))); // NOI18N
        btnAbout1.setText("¿QUIENES SOMOS?");
        btnAbout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbout1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAbout1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(112, 178, 156));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEtiqueta.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblEtiqueta.setForeground(new java.awt.Color(0, 0, 0));
        lblEtiqueta.setText("NOMBRE:");
        jPanel2.add(lblEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, 20));
        jPanel2.add(txtNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 340, 20));

        cbbTipoMascota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "GATO", "PERRO" }));
        jPanel2.add(cbbTipoMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 340, 20));

        ckbBuscNombre.setBackground(new java.awt.Color(112, 178, 156));
        buttonGroup1.add(ckbBuscNombre);
        ckbBuscNombre.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        ckbBuscNombre.setForeground(new java.awt.Color(0, 0, 0));
        ckbBuscNombre.setText("BUSCAR POR NOMBRE");
        ckbBuscNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbBuscNombreMouseClicked(evt);
            }
        });
        ckbBuscNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbBuscNombreActionPerformed(evt);
            }
        });
        jPanel2.add(ckbBuscNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        ckbBuscTipo.setBackground(new java.awt.Color(112, 178, 156));
        buttonGroup1.add(ckbBuscTipo);
        ckbBuscTipo.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        ckbBuscTipo.setForeground(new java.awt.Color(0, 0, 0));
        ckbBuscTipo.setText("BUSCAR POR TIPO");
        ckbBuscTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbBuscTipoMouseClicked(evt);
            }
        });
        jPanel2.add(ckbBuscTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        tblMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_MASCOTA", "NOMBRE", "EDAD", "TIPO", "DUENO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMascotas);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 680, 260));

        jPanel4.setBackground(new java.awt.Color(112, 178, 156));

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        btnInicio.setText("VOLVER");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel4.add(btnInicio);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        btnLimpiar.setText("MODIFICAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel4.add(btnLimpiar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminar);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, 40));

        btnInicio1.setText("BUSCAR");
        btnInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, 20));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WIlliam Rehel Design © 2019");
        jPanel3.add(jLabel1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbBuscNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbBuscNombreMouseClicked


    }//GEN-LAST:event_ckbBuscNombreMouseClicked

    private void ckbBuscTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbBuscTipoMouseClicked
        if (ckbBuscTipo.isSelected()) {
            lblEtiqueta.setText("TIPO: ");
            cbbTipoMascota.setVisible(true);
            txtNombreMascota.setVisible(false);
            txtNombreMascota.setText("");

        }
    }//GEN-LAST:event_ckbBuscTipoMouseClicked

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        this.dispose();
        Inicio in = new Inicio();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
             ControladorMascota cm = new ControladorMascota();
             int fila = tblMascotas.getSelectedRow();
             int columna = 0;
             int pivote = (int)tblMascotas.getValueAt(fila, columna);
        try {
            cm.MascotaEliminar(pivote);
        } catch (Exception ex) {
            Logger.getLogger(MantenedorMascota.class.getName()).log(Level.SEVERE, null, ex);
        }
                            DefaultTableModel dtm =  (DefaultTableModel) tblMascotas.getModel();
        
        dtm.setRowCount(0);
             
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio1ActionPerformed
        ArrayList <Mascota> listaMascotas = new ArrayList<>();
        ControladorMascota cm = new ControladorMascota();
        if (ckbBuscNombre.isSelected()) {
            listaMascotas = cm.MascotaListar(this.txtNombreMascota.getText());
        } else {
            listaMascotas = cm.TipoListar((String) this.cbbTipoMascota.getSelectedItem());            
        }
        DefaultTableModel dtm =  (DefaultTableModel) tblMascotas.getModel();
        dtm.setRowCount(0);
        for (Mascota mascota: listaMascotas ) {
            Object[] fila = {
                mascota.getIdMascota(),
                mascota.getNomMascota(),
                mascota.getEdadMascota(),
                mascota.getTipoMascota(),
                mascota.isDuenio()
            };
            dtm.addRow(fila);
        }
        
    }//GEN-LAST:event_btnInicio1ActionPerformed

    private void ckbBuscNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbBuscNombreActionPerformed
        if (ckbBuscNombre.isSelected()) {
            lblEtiqueta.setText("NOMBRE: ");
            cbbTipoMascota.setVisible(false);
            txtNombreMascota.setVisible(true);
        }
    }//GEN-LAST:event_ckbBuscNombreActionPerformed

    private void btnAbout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbout1ActionPerformed
        this.dispose();
        VentanaAbout va = new VentanaAbout();
    }//GEN-LAST:event_btnAbout1ActionPerformed

    private void btnAlmacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenarActionPerformed
        this.dispose();
        AlmacenarMascota in = new AlmacenarMascota();
    }//GEN-LAST:event_btnAlmacenarActionPerformed

    private void btnMantenedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenedor1ActionPerformed
        this.dispose();
        MantenedorMascota mm = new MantenedorMascota();
    }//GEN-LAST:event_btnMantenedor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorMascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout1;
    private javax.swing.JButton btnAlmacenar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInicio1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMantenedor1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbTipoMascota;
    private javax.swing.JCheckBox ckbBuscNombre;
    private javax.swing.JCheckBox ckbBuscTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEtiqueta;
    private javax.swing.JTable tblMascotas;
    private javax.swing.JTextField txtNombreMascota;
    // End of variables declaration//GEN-END:variables
}
